const express = require('express')
const userController = require('../controllers/users')
const userForgot = require('../middlewares/forgot_email')
const userOTP = require('../middlewares/otp')
const { upload } = require('../middlewares/multer')
const { verifyAccessAdmin } = require('../middlewares/auth')
const router = express.Router()

router
  .post('/register', userController.register)
  .post('/login', userController.login)
  .post('/forgotpassword', userForgot.forgotPass)
  .patch('/resetpassword/:id', userController.resetPassword)
  .patch('/update/:id', upload, userController.updateUser)
  .patch('/updateImage/:id', upload, userController.updateImage)
  .patch('/setpin/:id', userController.setPin)
  .patch('/pinOTP/:id', userOTP.pinOTP)
  .post('/confirmpin/:id', userController.confirmPin)
  .patch('/increaseSaldo/:id', userController.increaseSaldo)
  .patch('/decreaseSaldo/:id', userController.decreaseSaldo)
  .get('/:id', userController.getUserById)
  .get('/', userController.getAllUser)
  .delete('/:id', verifyAccessAdmin, userController.deleteUser)

module.exports = router
